### ISSUE TITLE
desktop watermark question

### ISSUE THREAD

**Issue by brightendavid** [NephrenCake/Mark-Probe#5]
我做的是UDH框架的水印，文档没写好，栽了。我想请教一下，你们是怎么解决DDH类型水印计算时间的问题的，我之前因为耗时问题没选DDH的方法。

**Comment by NephrenCake** [comment]
问过组委会，说是能用gpu的，所以速度这块就象征性减少一些参数，没怎么管了。之前测的数据，裸模型本身能跑个170fps，在视频中推理37fps，cpu的话就3-5fps，如果只能cpu那确实不好搞。
